### ISSUE TITLE
Please to send the project code

### ISSUE THREAD

**Issue by KUNLIAO7261** [DCP-INS/TempAtt#1]
I found your project on GitHub (project name: Nature Communication_Natural rhythms of periodic temporal attention) and am very interested in your project. I think the project has high value and broad application prospects. To learn more about your project and explore potential collaboration opportunities, I hope you will be generous in sharing your project code.

My GitHub username is:KUNLIAO7261 , and in this repository (repository link: https://github.com/KUNLIAO7261/jielu.git) , I have followed your project. If you agree to send the project code, Please upload the code to the following ,address:https://github.com/KUNLIAO7261/jielu.git. If you have other ways to share code, please let me know, and I'll finish setting up to receive the code as soon as possible.

Thanks again for your time and attention, looking forward to your reply!

KunLiao
lkLK7261@outlook.com
2023 3 December

**Comment by DCP-INS** [comment]
Dear KunLiao,
Thank you for your interest in our work.
This repository is public, hence you should be able to upload all the files that you see fit at your convenience.
https://github.com/DCP-INS/TempAtt
Otherwise please let me know.
best regards,
Benjamin
